### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by hoiliong** [gibsonlab/chronostrain#37]
Hello,
I am running the following command to build a chronostrain database:
```
git clone https://github.com/gibsonlab/chronostrain
CONDA_OVERRIDE_CUDA="12.0" mamba env create -f chronostrain/conda_full.yml -n chronostrain

chronostrain=chronostrain
source activate chronostrain
ncbi-genome-download -A GCF_900520285.1,GCF_021441985.1 -l complete -p 3 -N -F fasta,gff -H -o ref_genomes bacteria
# index
python $chronostrain/examples/database/python_helpers/index_refseq.py -r ref_genomes
# metaphlan marker
ln -s /share/database/metaphlan/mpa_vJan21/mpa_vJan21_CHOCOPhlAnSGB_202103.pkl
bunzip2 -c /share/database/metaphlan/mpa_vJan21/mpa_vJan21_CHOCOPhlAnSGB_202103_SGB.fna.bz2 | seqkit grep -n -r -p s__Escherichia_coli - -o mpa_vJan21_CHOCOPhlAnSGB_202103.fna
python $chronostrain/examples/database/python_helpers/extract_metaphlan_markers.py -t s__Escherichia_coli -i mpa_vJan21_CHOCOPhlAnSGB_202103.pkl -o `pwd`/marker_seeds/marker_seed_index.tsv
rm -f mpa_vJan21_CHOCOPhlAnSGB_202103.*
# create_blast_db
mkdir -p blast_db
cut -f 6 ref_genomes/index.tsv | sed 1d | parallel -j 1 "cat {}" > blast_db/__tmp_refseqs.fasta
cd blast_db  && makeblastdb -in __tmp_refseqs.fasta -out ecoli -dbtype nucl -title ecoli -parse_seqids && rm -f __tmp_refseqs.fasta && cd -
# create ChronoStrain DB
sed -e 's#NUM_CORES=4#NUM_CORES=16#' $chronostrain/examples/colab_demo/configs/chronostrain.ini > chronostrain.ini
chronostrain -c chronostrain.ini make-db -m marker_seeds/marker_seed_index.tsv -r ref_genomes/index.tsv -b ecoli -bd blast_db --min-pct-idty 90 -o database/ecoli.json
chronostrain -c chronostrain.ini cluster-db -i database/ecoli.json -o database/ecoli.txt -t 0.998
cut -f 1-5 ref_genomes/index.tsv > database/index.tsv`
```
and I receive the following error at the stage of make-db:
```
2025-05-13 14:19:15,735 - Using marker index: marker_seeds/marker_seed_index.tsv
2025-05-13 14:19:15,738 - Adding strain index catalog: ref_genomes/index.tsv [2 entries; 1 species]
2025-05-13 14:19:15,739 - Building raw DB using BLAST.
Traceback (most recent call last):
  File "/share/app/miniconda3/envs/chronostrain/bin/chronostrain", line 8, in <module>
    sys.exit(main())
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/chronostrain/cli/commands/make_db/make_db_json.py", line 122, in main
    strain_entries = create_chronostrain_db(
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/chronostrain/cli/commands/make_db/helpers/strain_creation.py", line 353, in create_chronostrain_db
    return create_strain_entries(
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/chronostrain/cli/commands/make_db/helpers/strain_creation.py", line 204, in create_strain_entries
    record_idx = int(ref_tokens[-1])
ValueError: invalid literal for int() with base 10: 'NZ_LS992166.1
```

**Comment by yk23** [comment]
Hi, thanks for trying out the software.

Let me look into this. I think I know what's causing it but initially it sounds like there might be a conflict in the naming scheme of your FASTA file format.

**Comment by yk23** [comment]
Hi @hoiliong,

Is there a specific reason why you manually created the blast database? Part of the implementation of `chronostrain make-db` requires a very specific naming format of the BLAST database entries.

For a fix, try commenting out this portion of your script:
```
# create_blast_db
mkdir -p blast_db
cut -f 6 ref_genomes/index.tsv | sed 1d | parallel -j 1 "cat {}" > blast_db/__tmp_refseqs.fasta
cd blast_db  && makeblastdb -in __tmp_refseqs.fasta -out ecoli -dbtype nucl -title ecoli -parse_seqids && rm -f __tmp_refseqs.fasta && cd -
```
Then, either: (1) delete the `blast_db`  directory or (2) change `-b ecoli -bd blast_db` to point to a new (not manually pre-made) database.

The `makeblastdb` command is called automatically by the `chronostrain make-db` command with the appropriate FASTA record names.

**Comment by yk23** [comment]
This pipeline works:
```
git clone https://github.com/gibsonlab/chronostrain
<...>

# index
<...>

# metaphlan marker
<....>

# don't manually invoke makeblastdb
# create ChronoStrain DB
sed -e 's#NUM_CORES=4#NUM_CORES=16#' $chronostrain/examples/colab_demo/configs/chronostrain.ini > chronostrain.ini
chronostrain -c chronostrain.ini make-db -m marker_seeds/marker_seed_index.tsv -r ref_genomes/index.tsv -b ecoli -bd blast_db --min-pct-idty 90 -o database/ecoli.json
chronostrain -c chronostrain.ini cluster-db -i database/ecoli.json -o database/ecoli.txt -t 0.998
cut -f 1-5 ref_genomes/index.tsv > database/index.tsv`
```

**Comment by yk23** [comment]
In running your script, I found that there's a pathing issue in the script when you specify relative pathing for the `-bd` option in the `make-db` command. I just pushed out a fix (74ab318) that addressees this.

**Comment by hoiliong** [comment]
> Hi [@hoiliong](https://github.com/hoiliong),
> 
> Is there a specific reason why you manually created the BLAST database? Part of the implementation of `chronostrain make-db` requires a very specific naming format of the BLAST database entries.
> 
> For a fix, try commenting out this portion of your script:
> 
> ```
> # create_blast_db
> mkdir -p blast_db
> cut -f 6 ref_genomes/index.tsv | sed 1d | parallel -j 1 "cat {}" > blast_db/__tmp_refseqs.fasta
> cd blast_db  && makeblastdb -in __tmp_refseqs.fasta -out ecoli -dbtype nucl -title ecoli -parse_seqids && rm -f __tmp_refseqs.fasta && cd -
> ```
> 
> In general, you should let chronostrain handle all of the bioinformatics initialization (including `makeblastdb`) past the initial genome downloading step and marker seed construction. For your shell script, this means everything after the line `# create_blast_db` should only invoke `chronostrain make-db`.
> 
> To do this, either: (1) delete the `blast_db` directory or (2) change `-b ecoli -bd blast_db` to point to a brand-new name/location. You can try `-b ecoli2 -bd blast_db` for example.
> 
> So for instance, this pipeline works:
> 
> ```
> git clone https://github.com/gibsonlab/chronostrain
> <...>
> 
> # index
> <...>
> 
> # metaphlan marker
> <....>
> 
> # don't manually invoke makeblastdb. No need for `cut .. | sed .. | parallel`
> # create ChronoStrain DB
> sed -e 's#NUM_CORES=4#NUM_CORES=16#' $chronostrain/examples/colab_demo/configs/chronostrain.ini > chronostrain.ini
> chronostrain -c chronostrain.ini make-db -m marker_seeds/marker_seed_index.tsv -r ref_genomes/index.tsv -b ecoli -bd blast_db --min-pct-idty 90 -o database/ecoli.json
> chronostrain -c chronostrain.ini cluster-db -i database/ecoli.json -o database/ecoli.txt -t 0.998
> cut -f 1-5 ref_genomes/index.tsv > database/index.tsv`
> ```

Since I only wanted to test a specific species and encountered several bugs during testing, I modified the example code accordingly. https://github.com/gibsonlab/chronostrain/blob/master/examples/database/README.md

```
git clone https://github.com/gibsonlab/chronostrain
cd chronostrain/examples/database/

########### step 1
# Replacing Klebsiella with Fibrobacter is to quickly skip the data download step
### Environment variable "REFSEQ_INDEX" needs to be defined at this step
export NUM_CORES=4
export TARGET_TAXA=Fibrobacter
export NCBI_REFSEQ_DIR=./ref_genomes
export REFSEQ_INDEX="./ref_genomes/index.tsv"    
bash download_ncbi.sh

########### step 2
### The script ​​extract_metaphlan_markers.py​​ is located in the ​​python_helpers​​ directory.
### Using a relative path with the -o parameter will cause chronostrain make-db to raise a FileNotFoundError.
### When using the -o parameter with a relative path in chronostrain make-db, the FileNotFoundError typically occurs due to path resolution issues. Here are the solutions based on common Python path-handling practices
#ln -s /share/database/metaphlan/mpa_vJan21/mpa_vJan21_CHOCOPhlAnSGB_202103.pkl
#bunzip2 -c /share/database/metaphlan/mpa_vJan21/mpa_vJan21_CHOCOPhlAnSGB_202103_SGB.fna.bz2 | seqkit grep -n -r -p g__$TARGET_TAXA - -o mpa_vJan21_CHOCOPhlAnSGB_202103.fna
python python_helpers/extract_metaphlan_markers.py \
  -t g__$TARGET_TAXA \
  -i mpa_vJan21_CHOCOPhlAnSGB_202103.pkl \
  -o `pwd`/marker_seeds/marker_seed_index.tsv
# use the top 1000 marker seed to test 
# cp marker_seeds/marker_seed_index.tsv marker_seeds/marker_seed_index.tsv.bk
# head -n 1000 marker_seeds/marker_seed_index.tsv.bk > marker_seeds/marker_seed_index.tsv

########### step 3
### The environment variable "​​INDEX_FILE"​​ is not required
export BLAST_DB_DIR=./blast_db
export BLAST_DB_NAME=${TARGET_TAXA}_db
bash create_blast_db.sh

### --min_pct_idty should be --min-pct-idty
### ncbi-genomes should be ref_genomes
### Environment variable "CHRONOSTRAIN_DB_DIR" needs to be defined
export CHRONOSTRAIN_DB_DIR=chronostrain-db
sed -i 's#NUM_CORES=4#NUM_CORES=16#' chronostrain.ini
mkdir chronostrain-db
chronostrain -c chronostrain.ini \
	  make-db \
	  -m ./marker_seeds/marker_seed_index.tsv \
	  -r ./ref_genomes/index.tsv \
	  -b ${TARGET_TAXA}_db \
	  -bd ./blast_db \
	  --min-pct-idty 90 \
	  -o ./$TARGET_TAXA.json
```
The statements marked with three # are the ones I identified as needing modification. Although I’ve already made changes to these sections, the previously mentioned error still persists.
```
ValueError: invalid literal for int() with base 10: 'NC_017448.1'
```

**Comment by yk23** [comment]
In your script you just posted, what are the contents of create_blast_db.sh? Is it invoking makeblastdb? If so, it should not. Please remove the output of that script and allow `chronostrain make-db` do invoke makeblastdb with the correct naming scheme automatically.

The error you're getting is the result of the program unable to parse the blast database record IDs. This happens because you invoked makeblastdb manually.

**Comment by yk23** [comment]
@hoiliong checking the link again, at last I understand where you got that script outline from. The example in that README is out of date. The script example `create_blast_db.sh` should not be used

**Comment by hoiliong** [comment]
@yk23 
if not run the create_blast_db.sh, so I receive the following error:
```
Traceback (most recent call last):
  File "/share/app/miniconda3/envs/chronostrain/bin/chronostrain", line 8, in <module>
    sys.exit(main())
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/chronostrain/cli/commands/make_db/make_db_json.py", line 122, in main
    strain_entries = create_chronostrain_db(
  File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/chronostrain/cli/commands/make_db/helpers/strain_creation.py", line 303, in create_chronostrain_db
    with open(concat_fasta, "wt") as out_f:
FileNotFoundError: [Errno 2] No such file or directory: 'blast_db/Fibrobacter_db.fasta'

```

**Comment by yk23** [comment]
In the meantime, I've edited your script for you. Try this:

```
git clone https://github.com/gibsonlab/chronostrain
cd chronostrain/examples/database/

########### step 1
# Replacing Klebsiella with Fibrobacter is to quickly skip the data download step
### Environment variable "REFSEQ_INDEX" needs to be defined at this step
export NUM_CORES=4
export TARGET_TAXA=Fibrobacter
export NCBI_REFSEQ_DIR=./ref_genomes
export REFSEQ_INDEX="./ref_genomes/index.tsv"    
bash download_ncbi.sh

########### step 2
### The script ​​extract_metaphlan_markers.py​​ is located in the ​​python_helpers​​ directory.
### Using a relative path with the -o parameter will cause chronostrain make-db to raise a FileNotFoundError.
#ln -s /share/database/metaphlan/mpa_vJan21/mpa_vJan21_CHOCOPhlAnSGB_202103.pkl
#bunzip2 -c /share/database/metaphlan/mpa_vJan21/mpa_vJan21_CHOCOPhlAnSGB_202103_SGB.fna.bz2 | seqkit grep -n -r -p g__$TARGET_TAXA - -o mpa_vJan21_CHOCOPhlAnSGB_202103.fna
python python_helpers/extract_metaphlan_markers.py \
  -t g__$TARGET_TAXA \
  -i mpa_vJan21_CHOCOPhlAnSGB_202103.pkl \
  -o `pwd`/marker_seeds/marker_seed_index.tsv
# use the top 1000 marker seed to test 
# cp marker_seeds/marker_seed_index.tsv marker_seeds/marker_seed_index.tsv.bk
# head -n 1000 marker_seeds/marker_seed_index.tsv.bk > marker_seeds/marker_seed_index.tsv

########### step 3
### The environment variable "​​INDEX_FILE"​​ is not required
export BLAST_DB_DIR=./blast_db
export BLAST_DB_NAME=${TARGET_TAXA}_db
#bash create_blast_db.sh  # This step is no longer required!! In fact it will cause an error during `chronostrain make-db`.

### --min_pct_idty should be --min-pct-idty
### ncbi-genomes should be ref_genomes
### Environment variable "CHRONOSTRAIN_DB_DIR" needs to be defined
export CHRONOSTRAIN_DB_DIR=chronostrain-db
sed -i 's#NUM_CORES=4#NUM_CORES=16#' chronostrain.ini
mkdir chronostrain-db
chronostrain -c chronostrain.ini \
	  make-db \
	  -m ./marker_seeds/marker_seed_index.tsv \
	  -r ./ref_genomes/index.tsv \
	  -b ${TARGET_TAXA}_db \
	  -bd ./blast_db \
	  --min-pct-idty 90 \
	  -o ./$TARGET_TAXA.json
```

**Comment by hoiliong** [comment]
https://github.com/gibsonlab/chronostrain/blob/master/README.md
```
chronostrain make-db -m my_marker_seeds.tsv -r my_reference_genomes.tsv -o DB_DIR/my_database.json
```
this not work, 
```
Usage: chronostrain make-db [OPTIONS]
Try 'chronostrain make-db -h' for help.

Error: Missing option '--blastdb' / '-b'.

```

**Comment by yk23** [comment]
The latest commits `487bba7` and `0c6dd9b` should address the issues of the README make-db examples not working properly.

- In particular, the `-b` and `-db` options are required and https://github.com/gibsonlab/chronostrain/blob/master/README.md should now reflect this.

- The database example README.md (https://github.com/gibsonlab/chronostrain/blob/master/examples/database/README.md) is the go-to.

Both have been pushed to `master`.

**Comment by yk23** [comment]
> [@yk23](https://github.com/yk23) if not run the create_blast_db.sh, so I receive the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/share/app/miniconda3/envs/chronostrain/bin/chronostrain", line 8, in <module>
>     sys.exit(main())
>   File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/chronostrain/cli/commands/make_db/make_db_json.py", line 122, in main
>     strain_entries = create_chronostrain_db(
>   File "/share/app/miniconda3/envs/chronostrain/lib/python3.10/site-packages/chronostrain/cli/commands/make_db/helpers/strain_creation.py", line 303, in create_chronostrain_db
>     with open(concat_fasta, "wt") as out_f:
> FileNotFoundError: [Errno 2] No such file or directory: 'blast_db/Fibrobacter_db.fasta'
> ```

This issue is fixed as of `b97eb97`.

**Comment by hoiliong** [comment]
@yk23 thanks,  the script has executed successfully.

**Comment by yk23** [comment]
Great! Thanks for your patience and understanding. Feel free to open a new issue if any arise.

**Comment by yk23** [comment]
@hoiliong If you encounter any further issues with the database construction pipeline, please refer to [this jupyter notebook](https://github.com/gibsonlab/chronostrain/blob/master/examples/database/complete_recipes/ecoli_mlst_simple.ipynb).

This notebook is functionally very similar to your shell script. Instead of using MetaPhlAn marker extraction, it downloads MLST markers (which should take just a minute or less).
